AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  VPCPeering:
    Description: VPC Peering destination
    Type: String
    MinLength: '12'
    MaxLength: '12'
    Default: vpc-306e3755
    AllowedPattern: 'vpc-(\w{8})'
    ConstraintDescription: 'must be a start "vpc-" and 8 digit'
  VPCPeeringCidr:
    Description: VPC Peering destination
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 172.31.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  InstantDevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.10.0/24
      Tags:
      - Key: Name
        Value: InstantDevVPC
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: InstantDevIGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref InstantDevVPC
      InternetGatewayId: !Ref InternetGateway
  FrontendRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: AttachGateway
    Properties:
      VpcId: !Ref InstantDevVPC
      Tags:
      - Key: Name
        Value: InstantDevFrontendRoute
  FrontendRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref FrontendRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  FrontendSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: AttachGateway
    Properties:
      CidrBlock: 172.16.10.0/24
      MapPublicIpOnLaunch: 'true'
      VpcId: !Ref InstantDevVPC
      Tags:
      - Key: Name
        Value: InstantDevVPCFrontendSubnet
  FrontendSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FrontendSubnet
      RouteTableId: !Ref FrontendRouteTable
  DefaultSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DependsOn: InstantDevVPC
    Properties:
      GroupDescription: default security group
      VpcId: !Ref InstantDevVPC
      # Other VPC
      SecurityGroupIngress:
        - IpProtocol: "-1"
          CidrIp: 172.31.0.0/16
          FromPort: '0'
          ToPort: '65535'
  DefaultSecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    DependsOn: DefaultSecurityGroup
    Properties:
      GroupId: !Ref DefaultSecurityGroup
      IpProtocol: "-1"
      FromPort: '0'
      ToPort: '65535'
      SourceSecurityGroupId: !Ref DefaultSecurityGroup
  WebSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DependsOn: InstantDevVPC
    Properties:
      GroupDescription: http and https
      VpcId: !Ref InstantDevVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: '80'
          ToPort: '80'
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: '443'
          ToPort: '443'
  SshSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    DependsOn: InstantDevVPC
    Properties:
      GroupDescription: ssh
      VpcId: !Ref InstantDevVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: !Ref SSHLocation
          FromPort: '22'
          ToPort: '22'
  PeeringRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref VPCPeeringCidr
      RouteTableId: !Ref FrontendRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnection
  VPCPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref InstantDevVPC
      PeerVpcId: !Ref VPCPeering
  
