AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

      #  ElasticIPAssociate:
      #    Type: AWS::EC2::EIPAssociation
      #    Properties: 
      #      AllocationId: !GetAtt ElasticIP.AllocationId
      #      InstanceId: !Ref Instance

Outputs:
  ElasticIP.AllocationId:
    Value: !GetAtt 
      - ElasticIP.AllocationId
    Export:
      Name: !Sub '${AWS::StackName}-EIP'

