AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

      #  ElasticIPAssociate:
      #    Type: AWS::EC2::EIPAssociation
      #    Properties: 
      #      AllocationId: !GetAtt ElasticIP.AllocationId
      #      InstanceId: !Ref Instance
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: kter.jp.
      Name: dev.kter.jp
      Type: A
      TTL: '300'
      ResourceRecords:
        -  !Ref ElasticIP

Outputs:
  ElasticIPAllocationId:
    Value: !GetAtt ElasticIP.AllocationId
    Export:
      Name: !Sub '${AWS::StackName}-EIP'

